[project]
name = "crispy-octo-broccoli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pipdeptree>=2.23.4",
    "streamlit==1.35.0",
]
